import '../models/product_model.dart';

class MockDataService {
  static List<ProductModel> getSampleProducts() {
    final now = DateTime.now();
    
    return [
      // Electronics
      ProductModel(
        id: 'prod_001',
        name: 'Samsung Galaxy A54',
        nameAr: 'سامسونج جالاكسي A54',
        description: 'Latest Samsung smartphone with 128GB storage',
        descriptionAr: 'أحدث هاتف سامسونج بسعة تخزين 128 جيجا',
        price: 85000,
        category: 'Electronics',
        categoryAr: 'إلكترونيات',
        images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400'],
        merchantId: 'merchant_001',
        merchantName: 'Tech Store Khartoum',
        stockQuantity: 15,
        rating: 4.5,
        reviewCount: 128,
        isFeatured: true,
        createdAt: now.subtract(const Duration(days: 30)),
        tags: ['smartphone', 'samsung', 'electronics'],
      ),
      ProductModel(
        id: 'prod_002',
        name: 'HP Laptop Core i5',
        nameAr: 'لابتوب HP كور i5',
        description: 'HP Laptop with Intel Core i5, 8GB RAM, 256GB SSD',
        descriptionAr: 'لابتوب HP بمعالج إنتل كور i5، رام 8 جيجا، هارد SSD 256 جيجا',
        price: 155000,
        category: 'Electronics',
        categoryAr: 'إلكترونيات',
        images: ['https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400'],
        merchantId: 'merchant_001',
        merchantName: 'Tech Store Khartoum',
        stockQuantity: 8,
        rating: 4.7,
        reviewCount: 89,
        isFeatured: true,
        createdAt: now.subtract(const Duration(days: 25)),
        tags: ['laptop', 'hp', 'computer'],
      ),
      ProductModel(
        id: 'prod_003',
        name: 'Wireless Headphones',
        nameAr: 'سماعات لاسلكية',
        description: 'Bluetooth wireless headphones with noise cancellation',
        descriptionAr: 'سماعات بلوتوث لاسلكية مع خاصية إلغاء الضوضاء',
        price: 12500,
        category: 'Electronics',
        categoryAr: 'إلكترونيات',
        images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400'],
        merchantId: 'merchant_002',
        merchantName: 'Audio Plus',
        stockQuantity: 25,
        rating: 4.3,
        reviewCount: 156,
        isFeatured: false,
        createdAt: now.subtract(const Duration(days: 20)),
        tags: ['headphones', 'audio', 'wireless'],
      ),

      // Fashion
      ProductModel(
        id: 'prod_004',
        name: 'Men\'s Traditional Jalabiya',
        nameAr: 'جلابية رجالية تقليدية',
        description: 'Traditional Sudanese jalabiya made from premium cotton',
        descriptionAr: 'جلابية سودانية تقليدية من القطن الفاخر',
        price: 8500,
        category: 'Fashion',
        categoryAr: 'أزياء',
        images: ['https://images.unsplash.com/photo-1490114538077-0a7f8cb49891?w=400'],
        merchantId: 'merchant_003',
        merchantName: 'Sudan Fashion',
        stockQuantity: 30,
        rating: 4.6,
        reviewCount: 94,
        isFeatured: true,
        createdAt: now.subtract(const Duration(days: 15)),
        tags: ['fashion', 'traditional', 'jalabiya'],
      ),
      ProductModel(
        id: 'prod_005',
        name: 'Women\'s Toub',
        nameAr: 'توب نسائي',
        description: 'Elegant Sudanese toub with beautiful patterns',
        descriptionAr: 'توب سوداني أنيق بنقوش جميلة',
        price: 15000,
        category: 'Fashion',
        categoryAr: 'أزياء',
        images: ['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=400'],
        merchantId: 'merchant_003',
        merchantName: 'Sudan Fashion',
        stockQuantity: 20,
        rating: 4.8,
        reviewCount: 112,
        isFeatured: true,
        createdAt: now.subtract(const Duration(days: 10)),
        tags: ['fashion', 'traditional', 'toub'],
      ),
      ProductModel(
        id: 'prod_006',
        name: 'Sports Shoes',
        nameAr: 'حذاء رياضي',
        description: 'Comfortable sports shoes for running and exercise',
        descriptionAr: 'حذاء رياضي مريح للجري والتمارين',
        price: 18000,
        category: 'Fashion',
        categoryAr: 'أزياء',
        images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400'],
        merchantId: 'merchant_004',
        merchantName: 'Sports World',
        stockQuantity: 40,
        rating: 4.4,
        reviewCount: 203,
        isFeatured: false,
        createdAt: now.subtract(const Duration(days: 8)),
        tags: ['shoes', 'sports', 'fitness'],
      ),

      // Food & Grocery
      ProductModel(
        id: 'prod_007',
        name: 'Sudanese Dates - Premium',
        nameAr: 'تمور سودانية فاخرة',
        description: 'Fresh premium quality Sudanese dates, 1kg pack',
        descriptionAr: 'تمور سودانية طازجة فاخرة، عبوة 1 كيلو',
        price: 3500,
        category: 'Food',
        categoryAr: 'أغذية',
        images: ['https://images.unsplash.com/photo-1609327990630-7bf59a496c00?w=400'],
        merchantId: 'merchant_005',
        merchantName: 'Nile Foods',
        stockQuantity: 100,
        rating: 4.9,
        reviewCount: 287,
        isFeatured: true,
        createdAt: now.subtract(const Duration(days: 5)),
        tags: ['food', 'dates', 'organic'],
      ),
      ProductModel(
        id: 'prod_008',
        name: 'Hibiscus Tea (Karkadeh)',
        nameAr: 'شاي الكركديه',
        description: 'Natural Sudanese hibiscus tea, 250g pack',
        descriptionAr: 'شاي كركديه سوداني طبيعي، عبوة 250 جرام',
        price: 1200,
        category: 'Food',
        categoryAr: 'أغذية',
        images: ['https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400'],
        merchantId: 'merchant_005',
        merchantName: 'Nile Foods',
        stockQuantity: 150,
        rating: 4.7,
        reviewCount: 198,
        isFeatured: false,
        createdAt: now.subtract(const Duration(days: 3)),
        tags: ['beverage', 'tea', 'natural'],
      ),

      // Home & Kitchen
      ProductModel(
        id: 'prod_009',
        name: 'Traditional Coffee Pot',
        nameAr: 'إبريق القهوة التقليدي',
        description: 'Handmade traditional Sudanese coffee pot (Jebena)',
        descriptionAr: 'إبريق قهوة سوداني تقليدي صناعة يدوية (جبنة)',
        price: 4500,
        category: 'Home',
        categoryAr: 'منزل',
        images: ['https://images.unsplash.com/photo-1514066558159-fc8c737ef259?w=400'],
        merchantId: 'merchant_006',
        merchantName: 'Heritage Crafts',
        stockQuantity: 25,
        rating: 4.6,
        reviewCount: 76,
        isFeatured: false,
        createdAt: now.subtract(const Duration(days: 12)),
        tags: ['home', 'kitchen', 'traditional'],
      ),
      ProductModel(
        id: 'prod_010',
        name: 'Prayer Mat',
        nameAr: 'سجادة صلاة',
        description: 'Comfortable prayer mat with beautiful Islamic patterns',
        descriptionAr: 'سجادة صلاة مريحة بنقوش إسلامية جميلة',
        price: 2800,
        category: 'Home',
        categoryAr: 'منزل',
        images: ['https://images.unsplash.com/photo-1604608672516-f1b9b1a0e3b2?w=400'],
        merchantId: 'merchant_006',
        merchantName: 'Heritage Crafts',
        stockQuantity: 60,
        rating: 4.8,
        reviewCount: 145,
        isFeatured: true,
        createdAt: now.subtract(const Duration(days: 7)),
        tags: ['home', 'prayer', 'islamic'],
      ),
    ];
  }

  static List<String> getCategories() {
    return [
      'إلكترونيات',
      'أزياء',
      'أغذية',
      'منزل',
      'رياضة',
      'جمال',
    ];
  }

  static List<Map<String, String>> getCategoriesWithIcons() {
    return [
      {'name': 'إلكترونيات', 'icon': '📱'},
      {'name': 'أزياء', 'icon': '👔'},
      {'name': 'أغذية', 'icon': '🍎'},
      {'name': 'منزل', 'icon': '🏠'},
      {'name': 'رياضة', 'icon': '⚽'},
      {'name': 'جمال', 'icon': '💄'},
    ];
  }
}
